### ISSUE TITLE
objective-git

### ISSUE THREAD

**Issue by hannesa2** [gitx-community/gitx#5]
The first step which has do be done, is to have a fork of `objective-git` but not from https://github.com/gitx/objective-git 
I would fork the upstream from primary upstream
That means we need a fork of https://github.com/libgit2/objective-git and prepare our new fork with the changes from https://github.com/gitx/objective-git 

Doing that way we have the change to apply improvements from primary-upsteam in the future with ease

I don't have the power to add a repo here. Please add me to the group https://github.com/orgs/gitx-community/people then I can do it. An other way is, that you do it

**Comment by jspiro** [comment]
@hannesa2 Would you like to re-open this on gitx/gitx?

**Comment by hannesa2** [comment]
Here it is https://github.com/gitx/gitx/issues/207
Now, you can delete this organization
